// <auto-generated />
using Aegis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Aegis.Infrastructure.Migrations
{
    [DbContext(typeof(AegisDbContext))]
    [Migration("20260706235000_AddTitleGenerationRawResponse")]
    partial class AddTitleGenerationRawResponse
    {
    }
}
